#!/bin/bash

##############################################################################
# Simple script the builds Key9 utilities into static binaries for 
# distribution. 
##############################################################################

K9_UTIL="k9-tail"

EXCLUDE="plan9|ios|android|js"  # Don't build these binaries.

# Get list from Go and exclude certain builds

go tool dist list | grep -vE $EXCLUDE | while read IN
do 

	OS=`echo $IN | cut -f1 -d'/'`
	ARCH=`echo $IN | cut -f2 -d'/'`

	echo -n "Building for $OS [$ARCH]: "

	mkdir -p bin/$OS 2> /dev/null 

	echo -n "*"	
	env GOOS=$OS GOARCH=$ARCH go build -o bin/$OS/$K9_UTIL.$ARCH

	echo -n "*"
	gzip -9 bin/$OS/$K9_UTIL.$ARCH

	echo -n "*"
	sha256sum bin/$OS/$K9_UTIL.$ARCH.gz | cut -d' ' -f1 > bin/$OS/$K9_UTIL.$ARCH.gz-sha256.txt

	echo 

done
